//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platibus.SQL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonSQLCommands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonSQLCommands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Platibus.SQL.CommonSQLCommands", typeof(CommonSQLCommands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [PB_MessageQueues] ([QueueName], [MaxConcurrency], [MaxAttempts], [RetryDelay])
        ///SELECT @QueueName, @MaxConcurrency, @MaxAttempts, @RetryDelay
        ///WHERE NOT EXISTS (SELECT [QueueName] FROM [PB_MessageQueues] WHERE [QueueName]=@QueueName).
        /// </summary>
        internal static string InsertQueueCommand {
            get {
                return ResourceManager.GetString("InsertQueueCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [PB_QueuedMessages] ([MessageId], [QueueName], [MessageName], [Origination], [Destination], [ReplyTo], [Expires], [ContentType], [SenderPrincipal], [Headers], [MessageContent])
        ///SELECT @MessageId, @QueueName, @MessageName, @Origination, @Destination, @ReplyTo, @Expires, @ContentType, @SenderPrincipal, @Headers, @MessageContent
        ///WHERE NOT EXISTS (
        ///	SELECT [MessageID] FROM [PB_QueuedMessages]
        ///	WHERE [MessageId]=@MessageId AND [QueueName]=@QueueName).
        /// </summary>
        internal static string InsertQueuedMessageCommand {
            get {
                return ResourceManager.GetString("InsertQueuedMessageCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [MessageId], [QueueName], [MessageName], [Origination], [Destination], [ReplyTo], 
        ///	[Expires], [ContentType], [SenderPrincipal], [Headers], [MessageContent], 
        ///	[Attempts], [Acknowledged], [Abandoned]
        ///FROM [PB_QueuedMessages]
        ///WHERE [QueueName]=@QueueName 
        ///AND [Acknowledged] IS NULL
        ///AND [Abandoned] IS NULL
        ///AND ([Expires] IS NULL OR [Expires] &gt; @CurrentDate).
        /// </summary>
        internal static string SelectQueuedMessagesCommand {
            get {
                return ResourceManager.GetString("SelectQueuedMessagesCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [PB_MessageQueues]
        ///SET [MaxConcurrency]=@MaxConcurrency
        ///, [MaxAttempts]=@MaxAttempts
        ///, [RetryDelay]=@RetryDelay
        ///WHERE [QueueName]=QueueName.
        /// </summary>
        internal static string UpdateQueueCommand {
            get {
                return ResourceManager.GetString("UpdateQueueCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [PB_QueuedMessages]
        ///SET [Acknowledged]=@Acknowledged
        ///, [Abandoned]=@Abandoned
        ///, [Attempts]=@Attempts
        ///WHERE [MessageId]=@MessageId AND [QueueName]=@QueueName.
        /// </summary>
        internal static string UpdateQueuedMessageCommand {
            get {
                return ResourceManager.GetString("UpdateQueuedMessageCommand", resourceCulture);
            }
        }
    }
}
