//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platibus.SQL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MSSQLCommands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MSSQLCommands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Platibus.SQL.MSSQLCommands", typeof(MSSQLCommands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateObjects	&quot;IF OBJECT_ID(&apos;[PB_MessageQueues]&apos;) IS NULL
        ///BEGIN
        ///	CREATE TABLE [PB_MessageQueues]
        ///	(
        ///		[QueueName] VARCHAR(255) NOT NULL,
        ///		[MaxConcurrency] INT NOT NULL DEFAULT 0,
        ///		[MaxAttempts] INT NOT NULL DEFAULT 1,
        ///		[RetryDelay] INT NOT NULL DEFAULT 0,
        ///
        ///		CONSTRAINT [PB_MessageQueues_PK]
        ///			PRIMARY KEY NONCLUSTERED ([QueueName])
        ///	)
        ///END
        ///
        ///IF OBJECT_ID(&apos;[PB_Messages]&apos;) IS NULL
        ///BEGIN
        ///	CREATE TABLE [PB_QueuedMessages]
        ///	(
        ///		[MessageId] UNIQUEIDENTIFIER NOT NULL,
        ///		[QueueName] VARCHAR(255) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateObjects {
            get {
                return ResourceManager.GetString("CreateObjects", resourceCulture);
            }
        }
    }
}
